# SPDX-License-Identifier: MIT

image: quay.io/fedora-ostree-desktops/buildroot:43

stages:
  - build

build niri-caelestia:
  stage: build
  script:
    - just compose-image niri-caelestia
    - just upload-container niri-caelestia
  artifacts:
    paths:
      - .buildid
      - logs
    expire_in: 2 week
